# Jekyll Resume Theme

# Site settings
title: Keunhwan Resume
email: khgapa@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
# url: "http://mattcouchman.co.uk/jekyll-resume"
name: Keunhwan Kim
job: Robotics Researcher 
location: Korea Electronics Technology Institute, Bucheon, Republic of Korea
languages: HTML, CSS and Javascript
github_username:  khgapa
linkedin_username:  khgapa
email_address: khgapa@gmail.com

# Build settings
markdown: kramdown
